openapi: 3.1.0
x-stoplight:
  id: dd4a2d0985b96
info:
  title: V1 Schema
  version: '1.0'
  summary: V1 Schema
  description: V1 Schema
  contact:
    name: Marten Klitzke
    url: 'https://fleetyards.net'
    email: info@fleetyards.net
  license:
    name: GNU General Public License v3.0
    url: 'https://github.com/fleetyards/fleetyards/blob/main/LICENSE'
tags:
  - name: Images
    description: Images
  - name: Models
    description: Models
  - name: Videos
    description: Videos
servers:
  - url: 'http://api.fleetyards.test/v1'
    description: development
  - url: 'https://stage.fleetyards.net/api/v1'
    description: stage
  - url: 'https://api.fleetyards.net/v1'
    description: live
paths:
  /models:
    get:
      summary: Models Index
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Model-Minimal.yaml
              examples: {}
      operationId: get-models
      description: List of Models
  '/models/{slug}':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Detail
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Model-Complete.yaml
      operationId: get-models-slug
      description: Model Detail
  '/models/{slug}/images':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Images
      tags:
        - Models
        - Images
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
      operationId: get-models-slug-images
      description: Model Images
  '/models/{slug}/videos':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Videos
      tags:
        - Models
        - Videos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
      operationId: get-models-slug-videos
      description: Model Videos
components:
  schemas:
    Image:
      type: object
      examples:
        - id: 14d9aa21-b932-4c1f-b006-fa5c1154d28d
          name: IMG_2488-6a3464c6-a3a6-44b0-8639-d048dac7a1f5.JPG
          caption: null
          url: 'http://fleetyards.test/uploads/image/name/14/d9/aa21-b932-4c1f-b006-fa5c1154d28d/IMG_2488-6a3464c6-a3a6-44b0-8639-d048dac7a1f5.JPG'
          width: 3840
          height: 2160
          type: image/jpeg
          background: true
          smallUrl: 'http://fleetyards.test/uploads/image/name/14/d9/aa21-b932-4c1f-b006-fa5c1154d28d/small_IMG_2488-6a3464c6-a3a6-44b0-8639-d048dac7a1f5.JPG'
          bigUrl: 'http://fleetyards.test/uploads/image/name/14/d9/aa21-b932-4c1f-b006-fa5c1154d28d/big_IMG_2488-6a3464c6-a3a6-44b0-8639-d048dac7a1f5.JPG'
          model:
            id: bd062120-034e-4bdc-a979-9b02644b5f3c
            name: 600i Explorer
            slug: 600i-explorer
          gallery:
            id: bd062120-034e-4bdc-a979-9b02644b5f3c
            name: 600i Explorer
            slug: 600i-explorer
          createdAt: '2021-09-14T17:48:14Z'
          updatedAt: '2021-09-14T17:48:16Z'
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        caption:
          type: 'null'
        url:
          type: string
          format: uri
        width:
          type: integer
        height:
          type: integer
        type:
          type: string
        background:
          type: boolean
        smallUrl:
          type: string
          format: uri
        bigUrl:
          type: string
          format: uri
        model:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            slug:
              type: string
        gallery:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            slug:
              type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Video:
      type: object
      examples:
        - id: 6c5f649c-a7a6-45ee-a9b4-9881795f6af8
          url: 'https://www.youtube-nocookie.com/embed/gbCSQDhPOlk'
          videoId: gbCSQDhPOlk
          type: youtube
          createdAt: '2017-08-28T21:46:01Z'
          updatedAt: '2018-05-06T19:50:00Z'
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
          format: uri
        videoId:
          type: string
        type:
          type: string
          enum:
            - youtube
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
