openapi: 3.1.0
x-stoplight:
  id: dd4a2d0985b96
info:
  title: schema-v1
  description: FleetYards Api Schema V1
  summary: V1 Schema
  version: '1.0'
  contact:
    name: Marten Klitzke
    url: 'https://fleetyards.net'
    email: info@fleetyards.net
  license:
    name: GNU General Public License v3.0
    url: 'https://github.com/fleetyards/fleetyards/blob/main/LICENSE'
tags:
  - name: Images
    description: Images
  - name: Manufacturers
    description: Manufacturers
  - name: Models
    description: Models
  - name: Videos
    description: Videos
servers:
  - url: 'http://api.fleetyards.test/v1'
    description: development
  - url: 'https://stage.fleetyards.net/api/v1'
    description: stage
  - url: 'https://api.fleetyards.net/v1'
    description: live
paths:
  /models:
    get:
      summary: Models Index
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/model-minimal.yaml
              examples: {}
      operationId: get-models
      description: List of Models
  '/models/{slug}':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Detail
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/model.yaml
      operationId: get-models-slug
      description: Model Detail
  '/models/{slug}/images':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Images
      tags:
        - Models
        - Images
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/image.yaml
      operationId: get-models-slug-images
      description: Model Images
  '/models/{slug}/videos':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Videos
      tags:
        - Models
        - Videos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/video.yaml
              examples:
                example-1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    name: string
                    slug: string
                    storeImage: 'http://example.com'
                    storeImageLarge: 'http://example.com'
                    storeImageMedium: 'http://example.com'
                    storeImageSmall: 'http://example.com'
                    category: string
                    subCategory: string
                    subCategoryLabel: string
                    description: string
                    pricePerUnit: true
                    sellPrice: string
                    averageSellPrice: string
                    buyPrice: null
                    averageBuyPrice: null
                    rentalPrice1Day: null
                    averageRentalPrice1Day: null
                    rentalPrice3Days: null
                    averageRentalPrice3Days: null
                    rentalPrice7Days: null
                    averageRentalPrice7Days: null
                    rentalPrice30Days: null
                    averageRentalPrice30Days: null
                    locationLabel: string
                    confirmed: true
                    commodityItemType: string
                    commodityItemId: 9d3c6b62-2f02-4230-b8cd-3f9b67647f6d
                    shop:
                      id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      name: string
                      slug: string
                      type: string
                      typeLabel: string
                      stationLabel: string
                      location: null
                      locationLabel: string
                      rental: true
                      buying: true
                      selling: true
                      storeImage: 'http://example.com'
                      storeImageLarge: 'http://example.com'
                      storeImageMedium: 'http://example.com'
                      storeImageSmall: 'http://example.com'
                      refineryTerminal: true
                      station:
                        name: string
                        slug: string
                    url: 'http://example.com'
                    videoId: string
                    type: youtube
                    createdAt: '2019-08-24T14:15:22Z'
                    updatedAt: '2019-08-24T14:15:22Z'
      operationId: get-models-slug-videos
      description: Model Videos
  /manufacturers:
    get:
      summary: Manufacturers Index
      tags:
        - Manufacturers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/manufacturer.yaml
      operationId: get-manufacturers
      description: List of Manufacturers
components:
  schemas: {}
  securitySchemes:
    sessionCookie:
      name: FLTYRD
      type: apiKey
      in: cookie
      description: Session Cookie for Authentication
