openapi: 3.1.0
x-stoplight:
  id: dd4a2d0985b96
info:
  title: schema-v1
  description: FleetYards Api Schema V1
  summary: V1 Schema
  version: '1.0'
  contact:
    name: Marten Klitzke
    url: 'https://fleetyards.net'
    email: info@fleetyards.net
  license:
    name: GNU General Public License v3.0
    url: 'https://github.com/fleetyards/fleetyards/blob/main/LICENSE'
tags:
  - name: Lists
    description: Lists
  - name: Manufacturers
    description: Manufacturers
  - name: Models
    description: Models
servers:
  - url: 'http://api.fleetyards.test/v1'
    description: development
  - url: 'https://stage.fleetyards.net/api/v1'
    description: stage
  - url: 'https://api.fleetyards.net/v1'
    description: live
paths:
  /models:
    get:
      summary: Models Index
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/model-minimal.yaml
              examples: {}
      operationId: get-models
      description: List of Models
  '/models/{slug}':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Detail
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/model.yaml
      operationId: get-model
      description: Model Detail
  '/models/{slug}/images':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Images
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/image.yaml
      operationId: get-model-images
      description: Model Images
  '/models/{slug}/videos':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
        description: Slug of Model
    get:
      summary: Model Videos
      tags:
        - Models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/video.yaml
      operationId: get-model-videos
      description: Model Videos
  /manufacturers:
    get:
      summary: Manufacturers Index
      tags:
        - Manufacturers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/manufacturer.yaml
      operationId: get-manufacturers
      description: List of Manufacturers
  /lists:
    get:
      summary: All lists for given user
      tags:
        - Lists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/list.yaml
      operationId: get-lists
      description: List of Lists
  '/lists/{id}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of List
    get:
      summary: Get List Detail
      tags:
        - Lists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/list.yaml
        '404':
          description: Not Found
      operationId: get-list
      description: List Detail
components:
  schemas: {}
  securitySchemes:
    sessionCookie:
      name: FLTYRD
      type: apiKey
      in: cookie
      description: Session Cookie for Authentication
